### ISSUE TITLE
services/events

### ISSUE THREAD

**Issue by bradmontgomery** [copitux/python-github3#15]
Greetings! 

Is anyone doing any work to support the [events api](http://developer.github.com/v3/events/)?  If not, I'm interested in working on it.

**Comment by copitux** [comment]
I don't think so, it'd be wonderful if you could help ;)

**Comment by ghost** [comment]
Hi @bradmontgomery, how is the Event API implementation going so far? Let me know if I could give you a hand with this.

**Comment by bradmontgomery** [comment]
@alejandrogomez Sorry for the late reply, but I haven't gotten very far yet. In fact, I haven't even pushed anything to my fork, but here's the general idea that I had for this:
1. Build an `pygithub3.services.events` package modeled after the other services.
2. Within that, build an `Events` with attributes corresponding to the various events available.
3. Proxy `Issues` and `Repo` events to the existing implementation for those services.

I haven't looked too closely at the `Repo` events implementation so I'm not sure if it's complete. 

I'll try to push my progress out later today, and you're welcome to jump in and lead the work! If you've already done some work on this, I'd love to check it out and see if we can merge anything.

**Comment by toutouastro** [comment]
@bradmontgomery  You can just start with some code and I will help!

**Comment by bradmontgomery** [comment]
For those interested, my initial work is here: https://github.com/bradmontgomery/python-github3/commit/edff0e8bda7e55a5dc1e8079a82160563067f1f8 

Feel free to jump in. Feedback is welcome!

I won't have a chance to do much over the next two days, but following that I hope to spend a lot of time on this.

**Comment by ghost** [comment]
@bradmontgomery cool, I'm not going to be able to review it for the next two days but I will take a look on tuesday.

**Comment by toutouastro** [comment]
@bradmontgomery I'll check that later :D

**Comment by copitux** [comment]
merged #20
